version: '3'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8090:8090"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8090"
    env_file:
      - .env
    volumes:
      - ./bd.db:/app/db.db:delegated

